version: 2.1

aliases:
  - &workspace_root my_workspace
  - &create_workspace
    run:
      name: create workspace
      command: |
        mkdir -p my_workspace/
        echo "Trying out workspace" > my_workspace/echo-output

jobs:
  one:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: 
          name: echo API KEY
          command: |
            curl -I ${URL}
      - *create_workspace
      - persist_to_workspace: 
          root: *workspace_root
          paths:
            - .
      - store_artifacts:
          path: *workspace_root 
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "A second hello"
      - attach_workspace:
          at: *workspace_root
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspace" ]]; then
            echo "It Workeds"
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
